config/routes.rb
Rails.application.routes.draw do
  resources :secret_codes
  resource :users
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  post  'requests' => 'users#code_request', as: :request_create_create
  root to: 'home#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  class Ability
    include CanCan::Ability
    def initialize(user)
      user ||= User.new
      if user.admin?
        can :read, :all
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles

  belongs_to :resource,
             :polymorphic => true,
             :optional => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/secret_code.rb
class SecretCode < ApplicationRecord
  #belongs_to :user
  belongs_to :user, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_one :secret_code

  def admin?
    has_role?(:admin)
  end
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception



  protected

  # def after_sign_in_path_for(resource)
  #   if resource.sign_in_count == 1 && resource.image.blank?
  #     user_profile_photo_path
  #   else
  #     #super
  #     session[:previous_url] || current_user
  #   end
  # end


  def after_sign_up_path_for(resource)

  end


  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user_params|
      user_params.permit(:username, :email, :fname, :lname, :password, :password_confirmation)
    end
    # devise_parameter_sanitizer.permit(:account_update) do |user_params|
    #   user_params.permit(:username, :email, :name, :avatar, :about, :password, :password_confirmation, :current_password, :crop_x, :crop_y, :crop_w, :crop_h)
    # end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/secret_codes_controller.rb
class SecretCodesController < ApplicationController
  before_action :set_secret_code, only: [:show, :edit, :update, :destroy]

  # GET /secret_codes
  # GET /secret_codes.json
  def index
    @secret_codes = SecretCode.all
  end

  # GET /secret_codes/1
  # GET /secret_codes/1.json
  def show
  end

  # GET /secret_codes/new
  def new
    @secret_code = SecretCode.new
  end

  # GET /secret_codes/1/edit
  def edit
  end

  # POST /secret_codes
  # POST /secret_codes.json
  def create
    @secret_code = SecretCode.new(secret_code_params)
    @secret_code[:user_id] = params[:user_id]
    if @secret_code.present?
      respond_to do |format|
        if @secret_code.save
          ##@secret_code.user.update_attributes(id: params[:user_id])
          format.html { redirect_to @secret_code, notice: 'Secret code was successfully created.' }
          format.json { render :show, status: :created, location: @secret_code }
        else
          format.html { render :new }
          format.json { render json: @secret_code.errors, status: :unprocessable_entity }
        end
      end
    else
      byebug
      @secret_code.save
      redirect_to :back
    end

  end

  # PATCH/PUT /secret_codes/1
  # PATCH/PUT /secret_codes/1.json
  def update
    respond_to do |format|
      if @secret_code.update(secret_code_params)
        format.html { redirect_to @secret_code, notice: 'Secret code was successfully updated.' }
        format.json { render :show, status: :ok, location: @secret_code }
      else
        format.html { render :edit }
        format.json { render json: @secret_code.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /secret_codes/1
  # DELETE /secret_codes/1.json
  def destroy
    @secret_code.destroy
    respond_to do |format|
      format.html { redirect_to secret_codes_url, notice: 'Secret code was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_secret_code
    @secret_code = SecretCode.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def secret_code_params
    params.require(:secret_code).permit(:secret_code)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def index
    @user = User.all
  end

  def create
    # Add a field for foobar with registration page
    @user = User.new(user_params)
    @secret_code = params[:search]
    if @secret_code == "foobar"
      @user.save!
      redirect_to secret_codes_path
    else
      render 'new'
    end
  end

  def code_request
    # foobar is default secret code is attached with send email
    @secret_code = "foobar"
    @user = params[:email]
    if @secret_code.present?
      UserMailer.with(user: @user, secret_code: @secret_code ).welcome_email.deliver_later
      redirect_to secret_codes_path
    end
  end

  private

  def user_params
    params.require(:user).permit!#(:email, :password, :password_confirmation, :secret_code)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def users_name
    @users = User.order('email').all
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/secret_codes_helper.rb
module SecretCodesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div> send secret code to this email </div>
<%= form_with url: request_create_create_path do  |f|%>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<html>
  <head>
    <title>Shop</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <nav class="navbar navbar-inverse navbar-top navbar-fixed-top">
      <div class="container-fluid">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="" href="/">Welcome to my App</a>
          </div>
        </div>
      </div>
    </nav>
    <div id="main-container" class="container">
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Profile <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%#= link_to "Edit profile", edit_user_registration_path %></li>
            <li><%= link_to "Sign up", new_user_registration_path %></li>
            <li><%= link_to "Login", new_user_session_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
      </ul>
      <% if user_signed_in? %>
        <li><%= link_to "Edit profile", edit_user_registration_path %></li>
      <% else %>
        <li><%= link_to "Sign up", new_user_registration_path %></li>
        <li><%= link_to "Login", new_user_session_path %></li>
      <% end %>
      <% if user_signed_in? %>
        <li role="separator" class="divider"></li>
        <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/secret_codes/_form.html.erb
<%= form_with(model: secret_code, local: true) do |form| %>
  <% if secret_code.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(secret_code.errors.count, "error") %> prohibited this secret_code from being saved:</h2>
      <ul>
        <% secret_code.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :secret_code %>
    <%= form.text_field :secret_code, id: :secret_code_secret_code %>
  </div>
  <div class="col-sm-8">
    <%= select_tag 'user_id',options_from_collection_for_select(users_name, 'id', 'email'), :prompt => "Select user", :class => "form-control", style: "background-color: #eee;"%>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/secret_codes/edit.html.erb
<h1>Editing Secret Code</h1>

<%= render 'form', secret_code: @secret_code %>

<%= link_to 'Show', @secret_code %> |
<%= link_to 'Back', secret_codes_path %>

app/views/secret_codes/index.html.erb
<h2>Secret Code List</h2>
<div class="product-block">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th class="col-md-2">Secret code</th>
        <th class="col-md-2"> User Associate with secret code</th>
      </tr>
    </thead>
    <tbody>
      <% @secret_codes.each do |secret_code| %>
        <tr>
          <td class="col-md-2"><%=secret_code.secret_code %></td>
          <% if secret_code.user.present? %>
            <td class="col-md-2">$<%=secret_code.user.email %></td>
          <%end%>
          <td class="col-md-4">
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<br>
<%= link_to 'New Secret Code', new_secret_code_path %>

app/views/secret_codes/new.html.erb
<h1>New Secret Code</h1>

<%= render 'form', secret_code: @secret_code %>

<%= link_to 'Back', secret_codes_path %>

app/views/secret_codes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Secret code:</strong>
  <%= @secret_code.secret_code %>
</p>

<%= link_to 'Edit', edit_secret_code_path(@secret_code) %> |
<%= link_to 'Back', secret_codes_path %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/index.html.erb
<% @users.each do |usr| %>
  <%= usr.email %>
<% end %>

app/views/users/new.html.erb
<h1>
  <div> Please Try again, The secret code is wrong
    <div></h1>